# Generated by Django 5.0.6 on 2024-05-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='nickname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
